### ISSUE TITLE
The status format is invalid message comes even the format is correct

### ISSUE THREAD

**Issue by rumeshbandara** [mpellegrin/nagios-eventhandler-cachet#9]
When I'm trying to create an event, I get the following error laravel.log

production.ERROR: exception 'AltThree\Validator\ValidationException' with message 'Validation has failed.' in /var/www/Cachet/vendor/alt-three/validator/src/ValidatingObserver.php:89
Validation errors:
The status format is invalid.

Tried this as explained in doc.

./cachet_notify  my.website apache CRITICAL HARD 'The service is DOWN'

**Comment by bugz8unny69** [comment]
I reported this issue upstream, see CachetHQ/Cachet#1789. 

Here's my working copy https://scm.lhprojects.net/LHProjects-Network/Scripts/files/db154bb6ca895d4ce1582b31f4cc174ce3b6a8d4/cachet_notify.

Regards

**Comment by NDKilla** [comment]
Note that since @lhorace 's link doesn't work for me, I figured I'd include the script I added to Miraheze's puppet repo. Note that the api token and url have to be changed from this, but it adds component_states :)

https://github.com/miraheze/puppet/commit/086ed60a955ff6e9893204f6a52aebf9623d92e3

**Comment by bugz8unny69** [comment]
@NDKilla Great! And btw, my link is fixed now. 

Additionally, I created a slightly improved version here https://scm.lhprojects.net/LHProjects-Network/Scripts/files/2c99db69699164f8985c7f73bc635ff63647b73e/cachet_notifyV2.php. AFAIK, it works!

Regards
